[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_staking_rust = "63uB2o4jHubS5RJUWYt8QwAp74RqzBrt4Eci3rzgL7sC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
